random_seed: 1
deterministic: False

dataset:
  type: &dataset_type 'KITTI'
  root_dir: 'data/KITTIDataset'
  train_split: 'semi_eigen_clean'
#  fold: 1 #半监督有标签的折数1,2,3,4,5
#  percent: 30 #半监督的标签比例1,2,5,10,15,20,25,30,50
  test_split: 'val'
  batch_size: 4
  sup_size: 2 
  use_3d_center: True
  class_merging: False
  use_dontcare: False
  bbox2d_type: 'anno'  # 'proj' or 'anno'
  meanshape: False  # use predefined anchor or not
  writelist: ['Car']
  clip_2d: False

  aug_pd: True
  aug_crop: True

  random_flip: 0.5
  random_crop: 0.5
  scale: 0.05
  shift: 0.05

  depth_scale: 'normal'

semi_train_cfg: 
  sup_size: 2       
  freeze_teacher: True # 冻结教师
  sup_weight: 1 # 监督权重
  unsup_weight: 0.1 # 无监督权重
  consistency_weight: 0 #一致性损失的权重
  topk: 50
  cls_pseudo_thr: 0.5 # 类 pseudobox 阈值
  score_pseudo_thr: 0 # pseudobox 阈值
  min_pseudo_bbox_wh: (1e-2, 1e-2) # 最小 pseudobbox 宽度
semi_test_cfg: 
  predict_on: 'teacher'
mean_teacher_hook:
  momentum: 0.001
  interval: 1
  skip_buffer: True

model_name: 'monodetr'
model:
  num_classes: 3
  return_intermediate_dec: True
  device: 'cuda'

  # Backbone
  backbone: 'resnet50'
  train_backbone: True
  num_feature_levels: 4
  dilation: False
  position_embedding: 'sine'  # 'sine' or 'learned'
  masks: False

  # Depth predictor
  mode: LID
  num_depth_bins: 80
  depth_min: 1e-3
  depth_max: 60.0

  # Transformer
  with_box_refine: True
  two_stage: False
  use_dab: False
  use_dn: False
  two_stage_dino: False
  init_box: False
  enc_layers: 3
  dec_layers: 3
  hidden_dim: 256
  dim_feedforward: 256
  dropout: 0.1
  nheads: 8
  num_queries: 50
  enc_n_points: 4
  dec_n_points: 4
  # DN
  scalar: 5
  label_noise_scale: 0.2
  box_noise_scale: 0.4
  num_patterns: 0
  # Loss
  aux_loss: True

  # Loss coefficients
  cls_loss_coef: 2
  focal_alpha: 0.25

  bbox_loss_coef: 5
  giou_loss_coef: 2
  3dcenter_loss_coef: 10
  dim_loss_coef: 1
  angle_loss_coef: 1
  depth_loss_coef: 1
  depth_map_loss_coef: 1

  # Matcher
  set_cost_class: 2
  set_cost_bbox: 5
  set_cost_giou: 2
  set_cost_3dcenter: 10


optimizer:
  type: 'AdamW'
  lr: 0.0002
  weight_decay: 0.0001


lr_scheduler:
  type: 'step'  # 'step' or 'cos'
  warmup: False  # 5 epoches, cosine warmup, init_lir=0.00001 in default
  decay_rate: 0.1
  decay_list: [29000, 38280]


trainer:
  max_iteration: 45240
  val_iterval: 232
  val_begin: 15000
  dynamic_intervals: "[(29000,484),(38280,232)]"
  # save_interval: 22620 # checkpoint save interval (in iteration)
  # resume_model: True
  #pretrain_model: /data/ipad_3d/monocular/MonoDETR_semi_baseline/work_dir/best_teacher_car_moderate_iter_37584.pth
  save_all: False  # False for only savng the best and latest ckpts
  use_dn: False
  scalar: 5
  label_noise_scale: 0.2
  box_noise_scale: 0.4
  num_patterns: 0

tester:
  type: *dataset_type
  mode: single  # 'single' or 'all'; 'all' to evaluate all ckpts in the folder
  checkpoint: 195  # the start ckpt epoch for 'all'
  threshold: 0.2  # confidence filter
  topk: 50